[package]
name = "phenix-core"
version = "0.1.0"
edition = "2021"
publish = false
autotests = false

[package.metadata.phenix]
role = "passive-library"

[dependencies]
getrandom.workspace = true
phenix-sdk-macros = { path = "../phenix-sdk-macros" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
