[package]
name = "phenix-client-acp"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[package.metadata.phenix]
role = "passive-library"

[dependencies]
phenix-application-interface = { path = "../phenix-application-interface" }
phenix-core = { path = "../phenix-core" }
phenix-sdk-macros = { path = "../phenix-sdk-macros" }

[build-dependencies]
phenix-application-interface = { path = "../phenix-application-interface" }

[dev-dependencies]
futures.workspace = true
