[package]
name = "phenix-plugin-debug"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
phenix-core = { path = "../phenix-core" }
phenix-sdk-macros = { path = "../phenix-sdk-macros" }
phenix-plugin-context = { path = "../phenix-plugin-context" }
phenix-plugin-frontend = { path = "../phenix-plugin-frontend" }
phenix-plugin-jobs = { path = "../phenix-plugin-jobs" }
phenix-plugin-models = { path = "../phenix-plugin-models" }
phenix-plugin-planning = { path = "../phenix-plugin-planning" }
phenix-plugin-sessions = { path = "../phenix-plugin-sessions" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
