from pathlib import Path

path = Path("modules/phenix-acp.nix")
text = path.read_text()
marker = '''            jq -e '\n              .id == 2\n              and .status == "ok"\n              and .output.result == "session"\n              and .output.session.id == "product-smoke"\n            ' "$TMPDIR/restore.json" >/dev/null\n\n            touch "$out"\n'''
replacement = '''            jq -e '\n              .id == 2\n              and .status == "ok"\n              and .output.result == "session"\n              and .output.session.id == "product-smoke"\n            ' "$TMPDIR/restore.json" >/dev/null\n\n            printf '%s\\n' '{"id":3,"service":"phenix.artifacts@1","input":{"operation":"store","content":[112,114,111,100,117,99,116],"provenance":{"producer":"product-smoke","provider_identity":null,"configuration_identity":null,"source_observations":{}}}}' \\
              | phenix-harness > "$TMPDIR/artifact.json"\n            jq -e '.id == 3 and .status == "ok" and .output.response == "stored" and .output.reused == false' "$TMPDIR/artifact.json" >/dev/null\n\n            printf '%s\\n' '{"id":4,"service":"phenix.context@1","input":{"operation":"register","resource_id":"product:context","kind":"external","source":"product-smoke","scope":"workspace","content":[99,111,110,116,101,120,116]}}' \\
              | phenix-harness > "$TMPDIR/context.json"\n            jq -e '.id == 4 and .status == "ok" and .output.result == "registered" and .output.resource.descriptor.resource_id == "product:context"' "$TMPDIR/context.json" >/dev/null\n\n            printf '%s\\n' '{"id":5,"service":"phenix.execution@1","input":{"operation":"runnable_tasks"}}' \\
              | phenix-harness > "$TMPDIR/execution.json"\n            jq -e '.id == 5 and .status == "ok" and .output.response == "runnable_tasks"' "$TMPDIR/execution.json" >/dev/null\n\n            printf '%s\\n' '{"id":6,"service":"phenix.planning@1","input":{"operation":"create_objective","id":"product-objective","title":"Harness product parity","parent":null}}' \\
              | phenix-harness > "$TMPDIR/planning.json"\n            jq -e '.id == 6 and .status == "ok" and .output.response == "objective" and .output.objective.id == "product-objective"' "$TMPDIR/planning.json" >/dev/null\n\n            printf '%s\\n' '{"id":7,"service":"phenix.language@1","input":{"operation":"current_diagnostics","workspace_id":"product-workspace"}}' \\
              | phenix-harness > "$TMPDIR/language.json"\n            jq -e '.id == 7 and .status == "ok" and .output.response == "diagnostics" and .output.result == null' "$TMPDIR/language.json" >/dev/null\n\n            printf '%s\\n' '{"id":8,"service":"phenix.models.routing@1","input":{"operation":"list_profiles"}}' \\
              | phenix-harness > "$TMPDIR/models.json"\n            jq -e '.id == 8 and .status == "ok" and .output.kind == "profiles"' "$TMPDIR/models.json" >/dev/null\n\n            printf '%s\\n' '{"id":9,"service":"phenix.jobs@1","input":{"operation":"list"}}' \\
              | phenix-harness > "$TMPDIR/jobs.json"\n            jq -e '.id == 9 and .status == "ok" and .output.response == "resources"' "$TMPDIR/jobs.json" >/dev/null\n\n            printf '%s\\n' '{"id":10,"service":"phenix.frontend-services@1","input":{"operation":"catalog"}}' \\
              | phenix-harness > "$TMPDIR/frontend.json"\n            jq -e '.id == 10 and .status == "ok" and .output.response == "providers"' "$TMPDIR/frontend.json" >/dev/null\n\n            printf '%s\\n' '{"id":11,"service":"phenix.hooks@1","input":{"operation":"get_configuration","revision":"missing"}}' \\
              | phenix-harness > "$TMPDIR/hooks.json"\n            jq -e '.id == 11 and .status == "ok" and .output.response == "configuration" and .output.configuration == null' "$TMPDIR/hooks.json" >/dev/null\n\n            printf '%s\\n' '{"id":12,"service":"phenix.debug@1","input":{"operation":"snapshot"}}' \\
              | phenix-harness > "$TMPDIR/debug.json"\n            jq -e '.id == 12 and .status == "ok" and .output.response == "snapshot" and (.output.snapshot.services | to_entries | all(.value.available == true))' "$TMPDIR/debug.json" >/dev/null\n\n            printf '%s\\n' '{"id":13,"service":"phenix.workspace@1","input":{"operation":"shell","command":"printf harness-workspace"}}' \\
              | phenix-harness > "$TMPDIR/workspace.json"\n            jq -e '.id == 13 and .status == "ok" and .output.response == "process" and .output.exit_code == 0 and .output.stdout == "harness-workspace"' "$TMPDIR/workspace.json" >/dev/null\n\n            printf '%s\\n' '{"id":14,"service":"phenix.cli.discover@1","input":{"name":"jq"}}' \\
              | phenix-harness > "$TMPDIR/cli.json"\n            jq -e '.id == 14 and .status == "ok" and .output.name == "jq" and (.output.availability == "available" or .output.availability == "limited")' "$TMPDIR/cli.json" >/dev/null\n\n            touch "$out"\n'''
if text.count(marker) != 1:
    raise SystemExit(f"expected one product smoke marker, found {text.count(marker)}")
path.write_text(text.replace(marker, replacement, 1))
