[package]
name = "phenix-provider-sdk"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.phenix]
role = "passive-library"

[dependencies]
bytes.workspace = true
http.workspace = true
phenix-core = { path = "../phenix-core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
